### ISSUE TITLE
GPS coordinates

### ISSUE THREAD

**Issue by jdblischak** [wrightaprilm/2014-08-23-ttu#4]
I noticed that the GPS coordinates for this bootcamp point to Chicago. This causes the Google Maps link on the bootcamp site to open to Chicago instead of Texas, and this bootcamp also appears on the map on the SWC website as occurring in Chicago (which is how I stumbled across it).

I hope the preparation is going well. Good luck this weekend!

**Comment by wrightaprilm** [comment]
Sorry I'm so late in getting back to this. I'll fix that now - thanks for pointing it out!
